name: Scan de Securite DevSecOps

on: [push]

jobs:
  verification-securite:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 1. RECHERCHE DE SECRETS (Gitleaks)
      - name: Scan Gitleaks (Secrets)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 2. ANALYSE STATIQUE DU CODE SOURCE (Semgrep - SAST)
      - name: Scan Semgrep (Code Source)
        run: |
          pip install semgrep
          semgrep --config=auto --error

      # 3. ANALYSE DES DÉPENDANCES (Trivy - SCA)
      - name: Scan Trivy (Dependances)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      # 4. CONNEXION À DOCKER HUB
      - name: Connexion a Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. BUILD & PUSH L'IMAGE (Uniquement si tout est propre !)
      - name: Build et Push de l'image Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: sironavault/mon-app-soutenance:latest
