name: Scan de Securite DevSecOps

on: [push]

jobs:
  verification-securite:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Scan Gitleaks (Secrets)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan Trivy (Code & Dependances)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      # ---- NOUVELLE ÉTAPE : CONNEXION À DOCKER HUB ----
      - name: Connexion a Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---- NOUVELLE ÉTAPE : BUILD & PUSH L'IMAGE ----
      - name: Build et Push de l'image Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # REMPLACE "ton-pseudo" par ton vrai pseudo Docker Hub ci-dessous :
          tags: sironavault/mon-app-soutenance:latest
